server:
  port: 9010
turbine:
  app-config: WEB,CLOUD-USER,CLOUD-ORDER,CLOUD-GATEWAY
  cluster-name-expression: new String("default")
spring:
  zipkin:
    base-url: http://localhost:9009  #指定Zipkin server地址
    sleuth:
      sampler:
        probability: 1.0