server:
  port: 9004
  servlet:
    path: /
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      max-active: 20
      filters: stat
      url: jdbc:mysql://127.0.0.1:3306/user-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: '{cipher}edb9e0b245cbb83567f38152250227622859711566861eb85db43e6cee6174d5'
      password: '{cipher}43eba75f4f33e85123bdb2c83ec8005f2d9f5f4190998394da4921cb7208e1b5'
mybatis-plus:
  mapper-locations[0]: classpath*:**/mapper/**/*Mapper.xml
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 10000
  ConnectTimeout: 10000
