server:
    port: 9002
    servlet:
        path: /
spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: 100MB
    datasource:
        druid:
            db-type: com.alibaba.druid.pool.DruidDataSource
            max-active: 20
            filters: stat
            url: jdbc:mysql://127.0.0.1/order-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
            username: root
            password: password
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
                    thread:
                        timeoutInMilliseconds: 10000
ribbon:
    MaxAutoRetriesNextServer: 0
    ReadTimeout: 10000
    ConnectTimeout: 10000
eureka:
    instance:
        lease-expiration-duration-in-seconds: 15
        lease-renewal-interval-in-seconds: 5
    client:
        registry-fetch-interval-seconds: 5
